env: "development"
log_level: "debug"
ports:
  http: "3001"
  grpc: "9001"
postgres:
  host: "localhost:5433"
  database: "product-service"
  username: "irvan"
  password: "irvan123"
  sslmode: "disable"
  max_idle_conns: 2
  conn_max_lifetime: "1h"
  ping_interval: "5000ms"
  retry_attempts: 3
  timeout: 120
  timezone: "Asia/Jakarta"
disable_caching: false
cache_ttl: "15m"
redis:
  cache_host: "redis://localhost:6379/0"
  lock_host: "redis://localhost:6379/0"
  auth_cache_host: "redis://localhost:6379/0"
  auth_cache_lock_host: "redis://localhost:6379/0"
  dial_timeout: 5
  write_timeout: 2
  read_timeout: 2
  max_idle_conn: 20
  max_active_conn: 50
services:
  grpc:
    iam_target: "localhost:9000"
    idle_conn_pool: "100"
    max_conn_pool: "500"
rpc_server_timeout: "10s"
rpc_client_timeout: "1s100ms"