version: '3.8'

services:
  postgres:
    image: postgres:15
    user: "1000:1000"  # Set the user and group ID
    environment:
      POSTGRES_USER: irvan
      POSTGRES_PASSWORD: irvan123
      POSTGRES_DB: postgres
    ports:
      - "5432:5433"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  
