// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: pb/product_service/general.proto

package product_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindByProductIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids"`
}

func (x *FindByProductIDsRequest) Reset() {
	*x = FindByProductIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_product_service_general_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByProductIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByProductIDsRequest) ProtoMessage() {}

func (x *FindByProductIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_product_service_general_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByProductIDsRequest.ProtoReflect.Descriptor instead.
func (*FindByProductIDsRequest) Descriptor() ([]byte, []int) {
	return file_pb_product_service_general_proto_rawDescGZIP(), []int{0}
}

func (x *FindByProductIDsRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type FindByProductIDsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Product []*Product `protobuf:"bytes,1,rep,name=product,proto3" json:"product"`
}

func (x *FindByProductIDsResponse) Reset() {
	*x = FindByProductIDsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_product_service_general_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByProductIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByProductIDsResponse) ProtoMessage() {}

func (x *FindByProductIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_product_service_general_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByProductIDsResponse.ProtoReflect.Descriptor instead.
func (*FindByProductIDsResponse) Descriptor() ([]byte, []int) {
	return file_pb_product_service_general_proto_rawDescGZIP(), []int{1}
}

func (x *FindByProductIDsResponse) GetProduct() []*Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type FindByProductIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
}

func (x *FindByProductIDRequest) Reset() {
	*x = FindByProductIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_product_service_general_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByProductIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByProductIDRequest) ProtoMessage() {}

func (x *FindByProductIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_product_service_general_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByProductIDRequest.ProtoReflect.Descriptor instead.
func (*FindByProductIDRequest) Descriptor() ([]byte, []int) {
	return file_pb_product_service_general_proto_rawDescGZIP(), []int{2}
}

func (x *FindByProductIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindByProductIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Product *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product"`
}

func (x *FindByProductIDResponse) Reset() {
	*x = FindByProductIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_product_service_general_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByProductIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByProductIDResponse) ProtoMessage() {}

func (x *FindByProductIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_product_service_general_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByProductIDResponse.ProtoReflect.Descriptor instead.
func (*FindByProductIDResponse) Descriptor() ([]byte, []int) {
	return file_pb_product_service_general_proto_rawDescGZIP(), []int{3}
}

func (x *FindByProductIDResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

var File_pb_product_service_general_proto protoreflect.FileDescriptor

var file_pb_product_service_general_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x20, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x17, 0x46, 0x69, 0x6e, 0x64,
	0x42, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x51, 0x0a, 0x18, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x35, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52,
	0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x22, 0x28, 0x0a, 0x16, 0x46, 0x69, 0x6e, 0x64,
	0x42, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x50, 0x0a, 0x17, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a,
	0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x42, 0x14, 0x5a, 0x12, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pb_product_service_general_proto_rawDescOnce sync.Once
	file_pb_product_service_general_proto_rawDescData = file_pb_product_service_general_proto_rawDesc
)

func file_pb_product_service_general_proto_rawDescGZIP() []byte {
	file_pb_product_service_general_proto_rawDescOnce.Do(func() {
		file_pb_product_service_general_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_product_service_general_proto_rawDescData)
	})
	return file_pb_product_service_general_proto_rawDescData
}

var file_pb_product_service_general_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_product_service_general_proto_goTypes = []interface{}{
	(*FindByProductIDsRequest)(nil),  // 0: pb.product_service.FindByProductIDsRequest
	(*FindByProductIDsResponse)(nil), // 1: pb.product_service.FindByProductIDsResponse
	(*FindByProductIDRequest)(nil),   // 2: pb.product_service.FindByProductIDRequest
	(*FindByProductIDResponse)(nil),  // 3: pb.product_service.FindByProductIDResponse
	(*Product)(nil),                  // 4: pb.product_service.Product
}
var file_pb_product_service_general_proto_depIdxs = []int32{
	4, // 0: pb.product_service.FindByProductIDsResponse.product:type_name -> pb.product_service.Product
	4, // 1: pb.product_service.FindByProductIDResponse.product:type_name -> pb.product_service.Product
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_product_service_general_proto_init() }
func file_pb_product_service_general_proto_init() {
	if File_pb_product_service_general_proto != nil {
		return
	}
	file_pb_product_service_product_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_product_service_general_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByProductIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_product_service_general_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByProductIDsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_product_service_general_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByProductIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_product_service_general_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByProductIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_product_service_general_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_product_service_general_proto_goTypes,
		DependencyIndexes: file_pb_product_service_general_proto_depIdxs,
		MessageInfos:      file_pb_product_service_general_proto_msgTypes,
	}.Build()
	File_pb_product_service_general_proto = out.File
	file_pb_product_service_general_proto_rawDesc = nil
	file_pb_product_service_general_proto_goTypes = nil
	file_pb_product_service_general_proto_depIdxs = nil
}
